---
- name: install some base server
  yum:
    name: "{{ item }}"
    state: present
    update_cache: no
  with_items:
    - "@Development tools"
    - epel-release
    - ntp
    - telnet
    - "@chinese-support"
