---
- name: install some base server
  yum:
    name: "{{ item }}"
    state: present
    update_cache: no
  with_items:
    - "@Development tools"
    - epel-release
    - ntp
    - telnet
    - wget
    - "@chinese-support"
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
