---
- name: optimize sysctl tcpip setting
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: '^{{ item.name }}\s+=\s+.*$'
    state: present
  with_items: "{{ sysctl_tcp_param }}"

- name: enable sysctl tcpip setting
  shell: sysctl -p
